"""Add note field to MoodLog

Revision ID: f5134dcf0beb
Revises: 
Create Date: 2025-04-28 18:59:48.069057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5134dcf0beb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_log', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
